---

options:
  env:
    - "DOCKER_BUILDKIT=0"
  machineType: "N1_HIGHCPU_8"
  diskSizeGb: "20"
  dynamic_substitutions: true

substitutions:
  _IMAGE_REGISTRY: "eu.gcr.io"
  _IMAGE_NAME: "docker-buildx"
  _IMAGE_TAG: "latest"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "image"
      - "pull"
      - "docker/dockerfile:latest"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "image"
      - "build"
      - "--pull"
      - "--tag"
      - "${_IMAGE_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}"
      - "."
    env: []

images:
  - "${_IMAGE_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_TAG}"


tags:
  - "docker"
  - "docker-buildx"
